### ISSUE TITLE
repo not up to date

### ISSUE THREAD

**Issue by uhon** [yoeluk/paper-scala-js#1]
Hi yoeluk

Thank you for all the mapping to scala. I'm exited to get my hands on Paper.js with scala!
while using your snapthost from Sonatype, i discovered that some methods on objects are missing (like remove on a Path). I want to add them and send you a pull-request, but when i cloned the gihub-repo it didn't reflect the code on Sonatype-Artifactory. Did you miss to push?

Cheers uhon

**Comment by yoeluk** [comment]
I will take a look in 2 to 3h. I am not able to check it right now. I might have missed a push. Sorry for that!

**Comment by yoeluk** [comment]
It seemed that the imports were no longer correct. I updated the version and then there a lot more @js.native annotations needed. I added those rather mechanic though. Let me know if this works for you. I also re-published it (hopefully that worked too.

If all that is good for you hopefully you can add the missing methods. By the way, which methods were missing?

**Comment by yoeluk** [comment]
As it happens there was quite a bit out of place. I think that's all back together now. I am closing the issue. Feel free to reopen it isn't resolved for you.
